<?xml version="1.0"?>
<robot name="stick" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="cylinderLength" value="0.3" />
    <xacro:property name="cylinderRadius" value="0.005" />
    <xacro:property name="cylinderMass" value="0.0027" />
    <link name="base">
        <visual>
            <!-- with respect to the center of the cylinder -->
            <origin rpy="0 0 0" xyz="0 0 ${cylinderLength/2}"/>
            <geometry>
                <cylinder length="${cylinderLength}" radius="${cylinderRadius}" />
            </geometry>
            <material name="gray">
                <color rgba="0.5 0.5 0.5 1" />
            </material>
        </visual>

        <!-- similar to visual, can be different for safer zones/computation -->
        <collision>
            <origin rpy="0 0 0" xyz="0 0 ${cylinderLength/2}"/>
            <geometry>
                <cylinder length="${cylinderLength}" radius="${cylinderRadius}" />
            </geometry>
        </collision>

        <inertial>
            <origin rpy="0 0 0" xyz="0 0 ${cylinderLength/2}"/>
            
            <!-- in kgs -->
            <mass value="${cylinderMass}"/>

            <!-- calc from script -->
            <inertia ixx="2.0e-5" ixy="0.0" ixz="0.0" iyy="2.0e-5" iyz="0.0" izz="3.3e-8"/>
        </inertial>

    </link>

    <xacro:property name="sphereRadius" value="0.02" />
    <xacro:property name="sphereMass" value="0.0027" />
    <link name="top">
        <visual>
            <!-- shift origin to the top -->
            <origin rpy="0 0 0" xyz="0 0 ${cylinderLength}" />
            <geometry>
                <sphere radius="${sphereRadius}" />
            </geometry>
            <material name="red">
                <color rgba="1 0 0 1" />
            </material>
        </visual>

        <collision>
            <origin rpy="0 0 0" xyz="0 0 ${cylinderLength}" />
            <geometry>
                <sphere radius="${sphereRadius}" />
            </geometry>
        </collision>

        <inertial>
            <origin rpy="0 0 0" xyz="0 0 ${cylinderLength}"/>
            
            <!-- in kgs -->
            <mass value="${sphereMass}"/>

            <!-- calc from script -->
            <inertia ixx="7.2e-7" ixy="0.0" ixz="0.0" iyy="7.2e-7" iyz="0.0" izz="7.2e-7"/>
        </inertial>
    </link>

    <joint name="joint1" type="fixed">
        <parent link="top"/>
        <child link="base"/>
        <!-- with respect the parent reference -->
        <origin rpy="0 0 0" xyz="0 0 0" />
    </joint>

</robot>