<?xml version="1.0"?>
<robot name="stick" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="cylinderLength" value="1.0" />
    <xacro:property name="cylinderRadius" value="0.005" />
    <xacro:property name="cylinderMass" value="0.002" />
    <xacro:property name="cylinderIxx" value="${1/12 * cylinderMass * (3 * cylinderRadius**2 + cylinderLength**2)}" />
    <xacro:property name="cylinderIyy" value="${1/12 * cylinderMass * (3 * cylinderRadius**2 + cylinderLength**2)}" />
    <xacro:property name="cylinderIzz" value="${1/2 * cylinderMass * cylinderRadius**2}" />
    <link name="base">
        <visual>
            <!-- with respect to the center of the cylinder -->
            <origin rpy="0 0 0" xyz="0 0 ${cylinderLength/2}"/>
            <geometry>
                <cylinder length="${cylinderLength}" radius="${cylinderRadius}" />
            </geometry>
            <material name="gray">
                <color rgba="0.5 0.5 0.5 1" />
            </material>
        </visual>

        <!-- similar to visual, can be different for safer zones/computation -->
        <collision>
            <origin rpy="0 0 0" xyz="0 0 ${cylinderLength/2}"/>
            <geometry>
                <cylinder length="${cylinderLength}" radius="${cylinderRadius}" />
            </geometry>
        </collision>

        <inertial>
            <origin rpy="0 0 0" xyz="0 0 ${cylinderLength/2}"/>
            
            <!-- in kgs -->
            <mass value="${cylinderMass}"/>

            <!-- calc from script -->
            <inertia ixx="${cylinderIxx}" ixy="0.0" ixz="0.0" iyy="${cylinderIyy}" iyz="0.0" izz="${cylinderIzz}"/>
        </inertial>

    </link>

    <xacro:property name="sphereRadius" value="0.03" />
    <xacro:property name="sphereMass" value="0.006" />
    <xacro:property name="sphereIxx" value="${2/3 * sphereMass * sphereRadius**2}" />
    <xacro:property name="sphereIyy" value="${2/3 * sphereMass * sphereRadius**2}" />
    <xacro:property name="sphereIzz" value="${2/3 * sphereMass * sphereRadius**2}" />
    <link name="top">
        <visual>
            <!-- shift origin to the top -->
            <origin rpy="0 0 0" xyz="0 0 ${cylinderLength}" />
            <geometry>
                <sphere radius="${sphereRadius}" />
            </geometry>
            <material name="red">
                <color rgba="1 0 0 1" />
            </material>
        </visual>

        <collision>
            <origin rpy="0 0 0" xyz="0 0 ${cylinderLength}" />
            <geometry>
                <sphere radius="${sphereRadius}" />
            </geometry>
        </collision>

        <inertial>
            <origin rpy="0 0 0" xyz="0 0 ${cylinderLength}"/>
            
            <!-- in kgs -->
            <mass value="${sphereMass}"/>

            <!-- calc from script -->
            <inertia ixx="${sphereIxx}" ixy="0.0" ixz="0.0" iyy="${sphereIyy}" iyz="0.0" izz="${sphereIzz}"/>
        </inertial>
    </link>

    <joint name="joint1" type="fixed">
        <parent link="top"/>
        <child link="base"/>
        <!-- with respect the parent reference -->
        <origin rpy="0 0 0" xyz="0 0 0" />
    </joint>

</robot>